services:
  nginx:
    container_name: nginx
    restart: always
    depends_on:
      fastify:
        restart: false
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-k", "https://localhost/" ]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 2s
    build:
      context: nginx
    ports:
      - "443:443"
    volumes:
      - public:/srv/app/public
      - secrets:/run/secrets
    networks:
      - api

  fastify:
    container_name: fastify
    restart: always
    depends_on:
      mariadb:
        restart: false
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-k", "https://localhost:8080/ping" ]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 2s
    build:
      context: fastify
    environment: [ DB_HOST, DB_NAME, DB_USER_NAME, DB_USER_PASSWORD ]
    volumes:
      - secrets:/run/secrets:z
    networks:
      - api
      - database

  mariadb:
    container_name: mariadb
    restart: always
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "--silent", "--skip-ssl" ]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 2s
    build:
      context: mariadb
      args: [ DB_USER_HOST, DB_USER_NAME, DB_USER_PASSWORD, DB_NAME ]
    volumes:
      - database:/var/lib/mysql
    networks:
      - database

volumes:
  public:
    driver: local
    driver_opts:
      device: ./nginx/public
      type: none
      o: bind
  secrets:
    driver: local
    driver_opts:
      device: ./secrets
      type: none
      o: bind
  database:
    driver: local
    driver_opts:
      device: ./mariadb/data
      type: none
      o: bind

networks:
  api:
    driver: bridge
  database:
    driver: bridge
