import * as speakeasy from "speakeasy";
import * as qrcode from "qrcode";

// unique secret object (base32 key + otpauth url to generate qr and other unused values) for each user to store in DB
export function	generate2FASecret(username: string) {
	const secret = speakeasy.generateSecret({
		name: `ft_transcendence (${username})`,
		length: 20,
	});
	return secret;
}

// return qrcode image (base 64) to scan with google auth . to display in front at the first activation of 2fa
export async function generateQRCode(otpauthURL: string): Promise<string> {
	const qrCode = await qrcode.toDataURL(otpauthURL);
	return qrCode;
}


// compare base32 key(secret) stored in db with token(one time pass generated by google auth app) 
export function verify2FAToken(secret:string, token: string): boolean {
	const	verified = speakeasy.totp.verify({
		secret,
		encoding: "base32",
		token,
	});
	return verified;
}